name: Tests

on:
  push:
    branches: [main]

jobs:
  Bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install Node Modules
        run: npm install

      - name: Check Formatting
        run: npm run test

      - name: TypeScript Validation
        run: npm run build

  Push:
    needs: Bot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: tests-passed

      - name: Push to tests-passed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/main
          git push
